# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.height_input = QtWidgets.QLineEdit(self.centralwidget)
        self.height_input.setGeometry(QtCore.QRect(150, 50, 113, 22))
        self.height_input.setObjectName("height_input")
        self.wind_speed_input = QtWidgets.QLineEdit(self.centralwidget)
        self.wind_speed_input.setGeometry(QtCore.QRect(150, 90, 113, 22))
        self.wind_speed_input.setObjectName("wind_speed_input")
        self.exposure_category_input = QtWidgets.QComboBox(self.centralwidget)
        self.exposure_category_input.setGeometry(QtCore.QRect(150, 130, 113, 22))
        self.exposure_category_input.setObjectName("exposure_category_input")
        self.exposure_category_input.addItem("")
        self.exposure_category_input.addItem("")
        self.exposure_category_input.addItem("")
        self.exposure_category_input.addItem("")
        self.calculate_button = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(150, 170, 113, 32))
        self.calculate_button.setObjectName("calculate_button")
        self.result_display = QtWidgets.QLabel(self.centralwidget)
        self.result_display.setGeometry(QtCore.QRect(150, 220, 200, 22))
        self.result_display.setText("")
        self.result_display.setObjectName("result_display")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wind Load Calculator"))
        self.height_input.setPlaceholderText(_translate("MainWindow", "Height (m)"))
        self.wind_speed_input.setPlaceholderText(_translate("MainWindow", "Wind Speed (m/s)"))
        self.exposure_category_input.setItemText(0, _translate("MainWindow", "A"))
        self.exposure_category_input.setItemText(1, _translate("MainWindow", "B"))
        self.exposure_category_input.setItemText(2, _translate("MainWindow", "C"))
        self.exposure_category_input.setItemText(3, _translate("MainWindow", "D"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))
